package:
	rm -rf mycleantest
	sh install.sh $@ mycleantest

ant:
	rm -rf mycleantest
	sh install.sh $@ mycleantest

ag:
	rm -rf mycleantest
	sh install.sh $@ mycleantest

ack:
	rm -rf mycleantest
	sh install.sh $@ mycleantest

predictive:
	rm -rf mycleantest
	sh install.sh $@ mycleantest

tar-mode:
	rm -rf mycleantest
	sh install.sh $@ mycleantest

git-rebase-mode:
	rm -rf mycleantest
	sh install.sh $@ mycleantest

git-commit-mode:
	rm -rf mycleantest
	sh install.sh $@ mycleantest

magit:
	rm -rf mycleantest
	sh install.sh $@ mycleantest

helm:
	rm -rf mycleantest
	sh install.sh $@ mycleantest

keywiz:
	rm -rf mycleantest
	sh install.sh $@ mycleantest

clean:
	rm -rf mycleantest
	rm -f *~ .*~
	rm -f */*~ */.*~
