test6:
	emacs --no-init-file --batch -l ./build5.el

test5:
	emacs --no-init-file --batch -l ./build4.el

test4:
	emacs --no-init-file --batch -l ./build3.el

test3:
	emacs --no-init-file --batch -l ./build2.el -- dirtree

test2:
	emacs --no-init-file --batch -l ./build.el -- dirtree

test:
	emacs --no-init-file --batch -l ./build.el -- helm

clean:
	echo no-op
